package com.example.bomberman.screens;

public enum ScreenType {
    HOME_SCREEN, GAME_SCREEN, OPTION_SCREEN, STAGE_SCREEN, TIME_OUT_SCREEN, SCORE_SCREEN, PVP_SCREEN, CHANGE_COLOR_SCREEN, HELP_SCREEN, RULES_SCREEN, CONTROL_SCREEN
}